#!/bin/bash

PATH=""

for pathfile in /etc/paths.d/* /etc/paths; do
    if [ ! -f $pathfile ]; then
        continue
    fi
    while read -r pathline; do
        PATH+=$pathline:
    done < $pathfile
done

echo -n ${PATH%:}
